#==================================================
# SERVER & LOGS (DEV)
#=================================================
server.port=8080
logging.level.org.springframework=INFO
logging.level.com.appfitness=DEBUG

#==================================================
# DATABASE (DEV - PostgreSQL Local)
#=================================================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/appfitness_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:RooT@123}
spring.datasource.driver-class-name=org.postgresql.Driver

#==================================================
# JPA / HIBERNATE (DEV)
# 'update' facilita testes locais criando/atualizando tabelas automaticamente
#=================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#==================================================
# SECURITY & INTEGRATIONS (DEV)
#=================================================
jwt.secret=${JWT_SECRET:0fpnazrhbt2rBa5F3Tn175nqrxfAEtrwy0S2VhQFUro8AyIqKXrPWkqKieSHOL+GRqgVg1BqsIrNKFb2Xw6YPQ==}
jwt.expiration=86400000
gemini.api.key=${GEMINI_API_KEY:SUA_CHAVE_AQUI_DE_API}