# Força o perfil de desenvolvimento para rodar localmente sem erros
spring.profiles.active=dev

spring.application.name=appfitness

# Importação opcional de arquivos .env locais (se existirem)
spring.config.import=optional:file:.env[.properties],optional:file:../../.env[.properties]